version: '2.1'

# Services we are going to use when running
services:
  # Reverse proxy.
  reverse-nginx:
    container_name: reverse-nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/includes:/etc/nginx/includes
      - /etc/letsencrypt/live/aceinpink.social:/etc/ssl/private
    depends_on:
      - app


  # Backend instance that depends on database instance to start.
  app:
    restart: always
    image: activitypub:latest
    environment:
      - ENVIRONMENT=dev
    # Internal port 3500 should always match your backend defined port
    ports:
      - "3510:8080"