version: '2.1'

# Services we are going to use when running
services:
  # Backend instance that depends on database instance to start.
  backend:
    image: activitypub:latest
    mem_limit: 300m
    environment:
      - ENVIRONMENT=dev
    restart: always
    # Internal port 3500 should always match your backend defined port
    ports:
      - "3510:8080"
  # Reverse proxy.
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - "80:3510"
      - "443:3510"
    volumes:
      - /etc/nginx/aceinpink.social:/etc/nginx
      - /etc/letsencrypt/live/aceinpink.social:/etc/ssl/private