version: '2.1'

# Services we are going to use when running
services:
  # Reverse proxy.
  reverse-nginx:
    container_name: reverse-nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./keys:/keys


  # Backend instance that depends on database instance to start.
  app:
    restart: always
    image: activitypub:latest
    environment:
      - ENVIRONMENT=dev